import { Agent, Orchestration } from "./types";

export const MOCK_AGENTS: Agent[] = [
  {
    id: "pricing-architect",
    name: "pricing-architect",
    description:
      "Designs pricing strategies, revenue models, and market positioning frameworks. Expert in SaaS, usage-based, and freemium models.",
    github_url: "https://github.com/agentmarket/pricing-architect",
    owner: "agentmarket",
    avatar: "PA",
    primary_tier: "opus",
    skills: ["pricing-strategy", "revenue-modeling", "saas", "market-analysis", "architecture"],
    metrics: {
      avg_tokens_per_task: { haiku: 800, sonnet: 2100, opus: 3200 },
      success_rate: 0.91,
      tasks_completed: 847,
    },
    quality_score: 0.88,
    wallet: "0x1a2b3c4d5e6f7890abcdef1234567890abcdef12",
    registered_at: "2024-11-03T09:00:00Z",
  },
  {
    id: "copywriter-pro",
    name: "copywriter-pro",
    description:
      "Crafts high-converting landing pages, email sequences, and marketing copy. Specializes in SaaS, B2B, and developer tools.",
    github_url: "https://github.com/agentmarket/copywriter-pro",
    owner: "agentmarket",
    avatar: "CP",
    primary_tier: "sonnet",
    skills: ["copywriting", "landing-pages", "email-marketing", "saas", "conversion"],
    metrics: {
      avg_tokens_per_task: { haiku: 320, sonnet: 1100, opus: 2800 },
      success_rate: 0.94,
      tasks_completed: 2341,
    },
    quality_score: 0.91,
    wallet: "0x2b3c4d5e6f7890abcdef1234567890abcdef1234",
    registered_at: "2024-10-15T14:30:00Z",
  },
  {
    id: "seo-specialist",
    name: "seo-specialist",
    description:
      "Optimizes content for search engines with keyword research, meta generation, and semantic structuring.",
    github_url: "https://github.com/agentmarket/seo-specialist",
    owner: "agentmarket",
    avatar: "SS",
    primary_tier: "sonnet",
    skills: ["seo", "keyword-research", "content-optimization", "meta-tags", "schema-markup"],
    metrics: {
      avg_tokens_per_task: { haiku: 290, sonnet: 1400, opus: 3100 },
      success_rate: 0.88,
      tasks_completed: 1205,
    },
    quality_score: 0.83,
    wallet: "0x3c4d5e6f7890abcdef1234567890abcdef123456",
    registered_at: "2024-11-20T11:00:00Z",
  },
  {
    id: "faq-formatter",
    name: "faq-formatter",
    description:
      "Structures and formats FAQ sections, documentation, and knowledge bases with consistency and clarity.",
    github_url: "https://github.com/agentmarket/faq-formatter",
    owner: "agentmarket",
    avatar: "FF",
    primary_tier: "haiku",
    skills: ["formatting", "documentation", "faq", "markdown", "content-structure"],
    metrics: {
      avg_tokens_per_task: { haiku: 340, sonnet: 900, opus: 2200 },
      success_rate: 0.97,
      tasks_completed: 5892,
    },
    quality_score: 0.79,
    wallet: "0x4d5e6f7890abcdef1234567890abcdef12345678",
    registered_at: "2024-09-01T08:00:00Z",
  },
  {
    id: "tweet-thread-writer",
    name: "tweet-thread-writer",
    description:
      "Composes viral Twitter/X thread content from long-form ideas. Expert at hooks, structure, and engagement optimization.",
    github_url: "https://github.com/agentmarket/tweet-thread-writer",
    owner: "agentmarket",
    avatar: "TT",
    primary_tier: "sonnet",
    skills: ["twitter", "threads", "social-media", "copywriting", "engagement"],
    metrics: {
      avg_tokens_per_task: { haiku: 280, sonnet: 900, opus: 2400 },
      success_rate: 0.85,
      tasks_completed: 3120,
    },
    quality_score: 0.78,
    wallet: "0x5e6f7890abcdef1234567890abcdef1234567890",
    registered_at: "2024-12-01T16:00:00Z",
  },
];

export const DEMO_ORCHESTRATION: Orchestration = {
  id: "orch-demo-001",
  goal: "Launch a new SaaS product: design the pricing architecture, write the landing page copy, and format the FAQ section.",
  status: "completed",
  tasks: [
    {
      id: "task-001",
      description: "Design pricing architecture for the new SaaS product",
      tier: "opus",
      tier_reason: "Multi-step strategic reasoning about revenue models and market positioning",
      status: "done",
      agent: MOCK_AGENTS[0],
      actual_tokens: 3180,
      cost_eth: 0.000572,
      naive_cost_eth: 0.000477,
      started_at: "2024-12-15T10:00:05Z",
      completed_at: "2024-12-15T10:00:28Z",
    },
    {
      id: "task-002",
      description: "Write landing page copy for the SaaS product",
      tier: "sonnet",
      tier_reason: "Balanced writing task requiring creativity and conversion focus",
      status: "done",
      agent: MOCK_AGENTS[1],
      actual_tokens: 1092,
      cost_eth: 0.000044,
      naive_cost_eth: 0.000164,
      started_at: "2024-12-15T10:00:28Z",
      completed_at: "2024-12-15T10:00:41Z",
    },
    {
      id: "task-003",
      description: "Format and structure the FAQ section",
      tier: "haiku",
      tier_reason: "Simple formatting and content structuring task",
      status: "done",
      agent: MOCK_AGENTS[3],
      actual_tokens: 342,
      cost_eth: 0.0000004,
      naive_cost_eth: 0.0000513,
      started_at: "2024-12-15T10:00:41Z",
      completed_at: "2024-12-15T10:00:44Z",
    },
  ],
  naive_cost_eth: 0.0006923,
  actual_cost_eth: 0.0001164,
  saved_pct: 72.4,
  tx_hash: "0x7f9e1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a",
  created_at: "2024-12-15T10:00:00Z",
};
